version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -p 5432"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  domainservice.api:
    build:
      context: .
      dockerfile: ./CoinBot.Api/Dockerfile
    depends_on:
      domainservice.migration:
        condition: service_completed_successfully

  domainservice.migration:
    build:
      context: .
      dockerfile: ./CoinBot.Migration/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui

  cache:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
